sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t pvi25/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pvi25/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "Udemy course"
  env: "Udemycourse-env"
  bucket_name: "elasticbeanstalk-eu-north-1-965465782106"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCES_KEY
  secret_access_key: $AWS_SECRET_KEY
